fix question data not appearing
error: used List of Question Object instead of singular Object

When checking Question object, error occured because list cant be null